language: php

matrix:
  include:
    - php: 5.5
      dist: precise
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: precise
    - php: 5.6
      dist: trusty

script: php -r '$gd = gd_info(); var_dump($gd); exit((int) !$gd["FreeType Support"]);'

notifications:
  emails: false
