language: php
sudo: false

jobs:
  include:
    - &test_precise
      stage: test
      php: 5.5
      dist: precise
      env: DIST=precise
    - <<: *test_precise
      php: 5.6
    - &test_trusty
      stage: test
      php: 5.5
      dist: trusty
      env: DIST=trusty
    - <<: *test_trusty
      php: 5.6

script: |-
  php --version
  php -r '$gd = gd_info(); var_dump($gd); exit((int) !$gd["FreeType Support"]);'

notifications:
  email: false
