language: php
sudo: false

matrix:
  include:
    - php: 5.5
      dist: precise
      env: DIST=precise
    - php: 5.5
      dist: trusty
      env: DIST=trusty
    - php: 5.6
      dist: precise
      env: DIST=precise
    - php: 5.6
      dist: trusty
      env: DIST=trusty

script: php -r '$gd = gd_info(); var_dump($gd); exit((int) !$gd["FreeType Support"]);'

notifications:
  email: false
