language: php

matrix:
  include:
    - php: 5.5
      dist: precise
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: precise
    - php: 5.6
      dist: trusty

script: php -r 'var_dump(gd_info());'

notifications:
  emails: false
